### ISSUE TITLE
Recommendation: Modify the execution interval

### ISSUE THREAD

**Issue by kingcc** [maximousblk/claim-epic-freebies#2]
Workflow don't need to be executed every day, although this doesn't cause any extra damage unless you run out of your Actions limits.

```
0 0 * * FRI
```

**Comment by JourneyOver** [comment]
The main reason that this runs once every day is because the action might fail for various reasons (like the script getting hit with a captcha at login which causes the action to throw an error). So if you was to say be running it only once a week instead, you run the risk that you will miss a giveaway unless you check manually every week to see if it grabbed the free games, but then running this would be just pointless.

**Comment by maximousblk** [comment]
@JourneyOver Yes that is the exact reason. I see my instance fail atleast twice a week. If it were only on Friday, I'm sure it would miss many games.

@kingcc closing this.
